# @package _global_
dataset:
  name: atis
  path: ../data/atis
  intent_info_path: ../data/atis/intent_info
  description_type: d1_pattern
  uttr_len: 20
  desc_len: 15

experiment:
  intent_desc_first: false
  epochs: 4
  batch_size: 16
  accum_steps: 1
  seed: 0
  temperature: 0.5
  k_negative: 7
  mlm_percent: 0.2
  mlm_param: 1
  prompt_len: 6

scheduler:
  lr: 2e-5
  warmup_steps: 0.15