# @package _global_
dataset:
  name: bank
  path: ../data/bank
  intent_info_path: ../data/bank/intent_info
  description_type: d1_pattern
  uttr_len: 80
  desc_len: 25

experiment:
  intent_desc_first: false
  epochs: 7
  batch_size: 32
  accum_steps: 2
  seed: 0
  temperature: 0.5
  k_negative: 7
  mlm_percent: 0.2
  mlm_param: 1
  prompt_len: 8

scheduler:
  lr: 2e-5
  warmup_steps: 0.15